### ISSUE TITLE
Herokuish

### ISSUE THREAD

**Issue by Immortalin** [piku/piku#157]
Full compatibility with Heroku buildpacks makes migration and runtime support a lot easier

https://github.com/gliderlabs/herokuish

**Comment by chr15m** [comment]
Seems like something that could be supported via a plugin - #129.

**Comment by rcarmo** [comment]
I just don’t see it happening - `dokku` fills this space very nicely, and Piku was actually driven by the fact that I could not use `dokku` on ARM at the time because `herokuish` and 99% of buildpacks did not support ARM.

And for 80% of stuff that runs on Python, Node or Java, OS packages just work (and are arguably easier to maintain for simple projects).

I can run Piku today with zero changes on Intel, ARM32 and ARM64 straight off a distro install (and actually do that for a couple of my projects that are tested and deployed locally and then pushed to Azure and Scaleway). If I need some exotic runtime or something more complex, it’s way easier (for me, at least) to just build the containers and use Docker Compose or K8s...

**Comment by dwightmulcahy** [comment]
I agree with @rcarmo that would go against the "light and ez" moto of Piku.

**Comment by chr15m** [comment]
Can I close this?
