### ISSUE TITLE
piku-bootstrap fails if the user has an incorrectly installed Ansible

### ISSUE THREAD

**Issue by den1k** [piku/piku#168]
Failing to install bootstrap piku on a server using the steps from README.

```
> ./piku-bootstrap root@142.93.113.67
Bootstrapping piku onto root@142.93.113.67
Using built-in playbook: piku.yml
./piku-bootstrap: /usr/local/bin/ansible-playbook: /usr/local/opt/python/bin/python2.7: bad interpreter: No such file or directory
```

I found the `/docs` with more and sometimes conflicting information. Any hints how to resolve this?

**Comment by chr15m** [comment]
Sorry for the slow reply. The bug here appears to on your local system - Ansible has been installed globally into `/usr/local/bin/ansible-playbook` and with a hash-bang of `/usr/local/opt/python/bin/python2.7` which is missing on your system. The problem is that the bootstrap script will first try to use a locally installed Ansible if it exists. Maybe I should remove that and just have it rely on an Ansible it has installed itself. :thinking:
