### ISSUE TITLE
Link to "Build a web app fast (with piku)"

### ISSUE THREAD

**Issue by chr15m** [piku/piku#200]
@rcarmo check out this work by @amontalenti:

https://github.com/amontalenti/webappfast-piku#readme

We could also link to my Linux Conf talk, which is how he found Piku: https://www.youtube.com/watch?v=ec-GoDukHWk

**Comment by rcarmo** [comment]
This is pretty awesome. @amontalenti is welcome to contribute new docs, I love the style 😄

**Comment by amontalenti** [comment]
Hey @rcarmo & @chr15m! Fun to see this ping in Github this morning. Glad to contribute some variant of this README as docs/examples. I wrote it up originally to give an internal lightning talk at @Parsely / @Automattic.

**Comment by rcarmo** [comment]
Well, thank you as well for bringing it to the attention of those fine folk, I used to know people at @Automattic a few years back 😄 

I've been trying to muster enough attention span to polish `piku` a bit more during my summer break (a tough call given that I'm supposed to be offline), and this is serendipitous. I don't have any fixed ideas about how to add this, but there are multiple ways I can see it happening:

* Clone the repo (giving you full ownership, obviously) and add it as `webapp-tutorial` to the Piku org (trivial, zero friction, would be useful for newbies as is)
* Merge and update the current `README` et al (less trivial, would require more passes, still has the same doc discoverability issues)
* Adapt it as an online tutorial under `gh-pages`, so we have a nicer site (a bit more work, long-term thing - say up until Xmas, at our current breakneck pace of development :smile:, would make discoverability nicer)

None of the above are mutually exclusive, and I'm OK with "slow and gradual" since we're all busy people who should be enjoying their time off... Let me know what you guys thing.

**Comment by amontalenti** [comment]
I love all these ideas! Glad to help in any way you all think is appropriate.

**Comment by rcarmo** [comment]
Okay, so let’s start going down the list then :) I’ll fork your repo and give you ownership when I’m at a laptop (phone is ludicrously hard to use for that) and we’ll get things going…

**Comment by rcarmo** [comment]
Repo clone done, and I also added links to `piku.github.io` and the `README` for good measure. I suspect the next step would be to canvas the existing docs and start moving them to the site somehow (maybe just use Jekyll, as even though I'm not crazy about it it's already there anyway.)
