### ISSUE TITLE
Use pyenv to allow arbitrary Python versions

### ISSUE THREAD

**Issue by chr15m** [piku/piku#24]
@rcarmo what would you think of a PR which supported arbitrary versions of Python via [pyenv](https://github.com/pyenv/pyenv)?

I was thinking that if `PYTHON_VERSION` contains a detailed version number like `2.7.15` then pyenv could be invoked to do the work of installing the custom python version and sandboxing the app in there. This means users can be specific about exactly which version of Python they want to run their app under as some in the 3.x series have quite different features.

I could install pyenv during bootstrap if `piku-bootstrap` gets merged, or otherwise it could be [installed at this point](https://github.com/rcarmo/piku/blob/master/piku.py#L413) if not already installed. [Here are the installation instructions](https://github.com/pyenv/pyenv#installation).

A similar thing could be done for nodejs via [nvm](https://github.com/nvm-sh/nvm) down the track too.

**Comment by rcarmo** [comment]
I would be OK with it provided that it a) failed silently or defaulted to the closest available major version if `pyenv` isn't around (so that we can keep using `click` as the sole dependency) and b) it wouldn't add significantly to the single script file.

I am an _extremely heavy_ user of `pyenv` myself (I have Anaconda, PyPy and stable 2.7 and 3.7 versions installed with it on both Mac and WSL) and mulled using `.python-version` files in the repo to trigger that sort of behaviour, but keeping `piku` minimal (and solely dependent on Debian/Ubuntu core packages) came first...

**Comment by dwightmulcahy** [comment]
@chr15m are you going to do a PR for this?  I like this feature since I have needs for 3.6+ python.

**Comment by chr15m** [comment]
@dwightmulcahy no I haven't started working on a PR, but actually, you can probably do this already:

 * SSH into your Piku machine as `root` and then `su` to become `piku`.
 * Install `pyenv` as the `piku` user.
 * Use `pyenv` to install the versions of Python which you want available.
 * Commit a `.python-version` file into your project and push it up.

Let me know if this works for you.

**Comment by dwightmulcahy** [comment]
@chr15m I've installed pyenv along with pyenv-virtualenv it works when I do something local to the `piku` user but it was crashing when you push an app up to `piku` remote.  I started to track it down in `piku.py` where it was creating the virtualenv directory for the project/app since it was losing it there.  I ran out of time to work on it more but pyenv-virtualenv handles the directory structure different then virtualenv does so I'll have to dig in deeper when I have the clock cycles.

will update when I have it figured out.

**Comment by chr15m** [comment]
Sounds good, thanks for the update.

**Comment by dwightmulcahy** [comment]
#58 was for node, this issue was for python.  I believe it still should be open for now.

**Comment by rcarmo** [comment]
Ah. That was the default behaviour when I merged since this was referenced.

**Comment by chr15m** [comment]
Over on #53 @dwightmulcahy got another version of Python running using a uwsgi plugin.

I found more info on running different versions under a single uwsgi emperor here: https://serverfault.com/questions/633437/different-python-versions-under-the-same-uwsgi-emperor

I've been thinking about how to best support multiple Pythons and I've got a WIP over here (not stable or tested):
https://github.com/chr15m/piku/commit/3c8568dc33fcd43fe727be4683ce495916bd8e3d

Basically the idea is if the user has `pyenv` installed in `~/.pyenv` and they have `PYTHON_VERSION` set to some specific version it should install that version of python, and then could pick it up when setting up the virtualenv. Uwsgi is another matter and I guess it will also have to compile a uwsgi plugin for each version installed. Would be good to know what changes you made made to `piku.py` @dwightmulcahy in order to get that working on #53.

(btw should we close #53 now that you've solved that issue?)

**Comment by dwightmulcahy** [comment]
Ok... this is what I did to get it to support python3.7

(already had installed python 3.7 on my rpi)
Build plug-in for uwsgi:
```
apt-get install python3.7-dev uwsgi-src uuid-dev libcap-dev libpcre3-dev
PYTHON=python3.7 uwsgi --build-plugin "/usr/src/uwsgi/plugins/python python37"
```

added an `ENV` file to my project with this in it:
```
PYTHON_VERSION=37
```

this assured that the correct version of python was installed to the virtualenv that was created at this line: https://github.com/rcarmo/piku/blob/fc0abee262e92c427a44023f490c1fc3b6abfdb8/piku.py#L467
had to change it to this:
```
       if version > 3:
           version = version/10.0
       call('virtualenv --python=python{version} {app:s}'.format(**locals()), cwd=ENV_ROOT, shell=True)
```

had to add this to the end of this code: https://github.com/rcarmo/piku/blob/fc0abee262e92c427a44023f490c1fc3b6abfdb8/piku.py#L739-L759
```
        else:
            # handle versions outside of python 2/3
            settings.extend([
                ('plugin',      'python%s' % python_version),
            ])
```

This was a quick _hack_ so that I could get my app running under 3.7 in that there is no error checking and has several points of failure and only handles one situation of a python deployment.

**Comment by chr15m** [comment]
This is very helpful, thanks. I think there is enough here to help me get the pyenv branch finished.

**Comment by dwightmulcahy** [comment]
Cool.  One thing that would be nice is that `PYTHON_VERSION` could be either a MAJOR version number or MAJOR.MINOR.PATCH.  That way it would be backward compatible.

**Comment by rcarmo** [comment]
FYI, I just installed it on a new Pi running Debian Buster (which ships with Python 3.7). Also updated the manual install doc (since I wanted to make sure the package names were the same, etc.).

**Comment by chr15m** [comment]
@rcarmo that's great. I will try the `piku-bootstrap` script out on Raspian Buster too, assuming you didn't already.

**Comment by rcarmo** [comment]
I didn’t try the script because I did the setup via my iPad, but it should work.

**Comment by rcarmo** [comment]
I’ve been fiddling with `pyenv`, and just off the top of my head, there are a few things that need addressing:

* I personally tend to use `pyenv` as an evergreen install (I `git clone` it directly into `~/.pyenv` and update it regularly to fetch new Python versions), which makes it challenging to integrate with a distro-based `uwsgi` install.
* on the other hand, getting a `pyenv` Python interpreter to run as a standard `web` worker is pretty trivial (all you need is to fiddle with environment variables)

So I’m wondering if a simple `ENV` template and some guidelines wouldn’t suffice here.

Thoughts?

**Comment by chr15m** [comment]
> So I’m wondering if a simple ENV template and some guidelines wouldn’t suffice here.

@rcarmo do you mean to just support `web` worker model? I think that's a good start. If somebody finishes pyenv + distro-based `uswgi` working later then that could be merged separately.

Did you have time to look at https://github.com/chr15m/piku/commit/3c8568dc33fcd43fe727be4683ce495916bd8e3d?

**Comment by rcarmo** [comment]
> On 11 Aug 2019, at 07:38, Chris McCormick <notifications@github.com> wrote:
> Did you have time to look at chr15m@3c8568d?
> 

I did now :) have been either busy or off-grid. 

That seems to do what is necessary, although I don’t see a check for the `.python_version` file (might be in another commit). I’d say that if a Python project is pushed to Piku with a version market that matches what `pyenv` can provide locally then that would get invoked. etc. - maybe disabling `wsgi` as a precaution or issuing a warning about only being able to use web workers in the process?

Thinking out oud here.

**Comment by chr15m** [comment]
@rcarmo thank you for reviewing, I appreciate it. I'll add a check for `.python_version`. I will also see if I can get uwsgi working with plugins as @dwightmulcahy demonstrated, but if it's too ugly I'll default to what you said - showing the user a message.

**Comment by dwightmulcahy** [comment]
building the plugin for the `uwsgi` wasn't bad after installing the correct dependencies and I remember that it didn't take that long to execute either.
```
PYTHON=python3.7 uwsgi --build-plugin "/usr/src/uwsgi/plugins/python python37"
```
obviously, this would only be needed to be built if that plugin didn't exist yet.

I think that the uwsgi part could be a phase two type of thing.

**Comment by chr15m** [comment]
I have removed myself from this as I am no longer using Python. Anybody else who wants to get it working feel free to pick it up.
