### ISSUE TITLE
Nginx timeouts

### ISSUE THREAD

**Issue by Noonlord** [piku/piku#248]
It maybe benefical setting these to make nginx timeout 10 minutes. Currently it give gateway timeout 504 when a request takes too long. I fixed it on my machine locally by settings these on nginx.conf. 

Also I didnt have guts to try but can it be done with NGINX_INCLUDE_FILE as well? 

proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
send_timeout 600;

**Comment by rcarmo** [comment]
Hi there!

Theoretically yes, those seem like they could be set via an include (although I’m not sure if they’re top-level settings only, in which case we’d have to find a way to have them set via the `ENV` file). But to be perfectly candid, if your app is taking that long to reply then you should be looking at ways to do background processing (which is why `piku` supports multiple kinds of processes). 

My general rule of thumb is that anything taking more than a second of wall clock time needs to be done outside an HTTP request, since otherwise you’re just tying up resources at both the server and the client — hence there not being any need for that kind of tweaking in general.

**Comment by Noonlord** [comment]
That really makes sense, yeah. But I think being able to keep a request alive is somewhat useful in some cases. Like listening from a change from serverside, instead of spamming server with requests I keep one request alive and close the request when a change happens. I don't know if this is beneficial at all but it made more sense to me than spamming requests to server. A better option would be using websockets/socketio ofc.

**Comment by chr15m** [comment]
I was just about to suggest SSE.

https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events

@Noonlord one great thing about them is the browser maintains connection for you across disconnects.

Otherwise I think try the include file. I think nginx might also exempt websockets from the timeout so you might want to test that out.

**Comment by Noonlord** [comment]
Thanks to both of you! SSE seems great. Will check it out.
