### ISSUE TITLE
Static binary deployments with Piku

### ISSUE THREAD

**Issue by nii236** [piku/piku#269]
For projects that are not my own, but are available as compiled, static, single binaries, what is the process to get these into the Piku system?

Is it a requirement that I create a fresh repo, add and commit the compiled binary, then deploy it? Or is there a binary-native way to deploy an app?

Case study:

I am trying to deploy Prometheus, a monitoring system. Its not my project. I would normally:
- Download the binary
- Extract it somewhere
- Add systemd file
- Set-up reverse proxy

For Piku, I don't think I can deploy an app without a git repo setup first. Is this the case?

**Comment by rcarmo** [comment]
Hi there!

Well, Prometheus is the kind of thing you'd ordinarily deploy outside `piku` (I'd set it up as part of the host, likely using `cloud-init` since I mostly use virtual machines of various kinds), but you have more options besides packing the binary into `git` - for instance, you can use the `release` entry in `Procfile` to fetch the binary from a trusted location

I usually pack that kind of thing into a `Makefile` since they're a few steps involved, like getting the binary, checksumming it, etc. Also, you wouldn't need a `systemd` entry for it, since `uwsgi` would supervise the process (and the `piku` user is usually unprivileged, so at most you'd be able to use `release` to ensure there is a user-level unit entry someplace).

But in general, `piku` is aimed at self-managed projects and what you want to do falls outside the beaten path.

**Comment by rcarmo** [comment]
Hi again - I was reviewing our list of examples, and as it happens, [the Gitea example](https://github.com/piku/deploy-gitea) does the gist of what I outlined as a possible alternative.

**Comment by nii236** [comment]
Thanks @rcarmo, love Piku! Will check out the gitea example.

**Comment by chr15m** [comment]
@nii236 support for the static binary workflow could be better. I'll see if I can come up with a helper script for this flow.
