### ISSUE TITLE
What is fetcher?

### ISSUE THREAD

**Issue by jfmatth** [piku/piku#318]
Noticed ```fetcher``` in the DESIGN.md file regarding the Procfile and Python, yet no explanation.  Is this outdated?

**Comment by rcarmo** [comment]
It's just an example.

**Comment by jfmatth** [comment]
an example of what?  A Key

Does it have any function?  If not, we should remove it from the docs, it's confusing.

**Comment by rcarmo** [comment]
It's an example of a worker with a different name. I don't see why it is confusing. The sentences before it state that workers can have arbitrary names, and that `Procfiles` can be "like such". If you think that should be stated otherwise, feel free to submit a PR, but it should make it plain that workers can have arbitrary names.

**Comment by jfmatth** [comment]
Ah, right.  I didn't realize that so thanks for pointing it out.  No need for a PR
