### ISSUE TITLE
Windows support 

### ISSUE THREAD

**Issue by steskalja** [piku/piku#347]
Are there any plans for Windows support? Otherwise you are missing out on over 2+ billion devices.

**Comment by chr15m** [comment]
Do you mean Windows as the server or the local? If the local then the Piku local script should run fine in WSL.

**Comment by jfmatth** [comment]
You should be able to run a hyper-v Linux VM and get the same functionality

**Comment by rcarmo** [comment]
It works on WSL (and an earlier version worked on Cygwin). Making it fully Windows native is not impossible, but not without some major replumbing that we could not devote the time to test and maintain.On 9 Jun 2024, at 19:38, steskalja ***@***.***> wrote:﻿[piku/piku] Windows support (Issue #347)Are there any plans for Windows support? Otherwise you are missing out on over 2+ billion devices.—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you are subscribed to this thread.Triage notifications on the go with GitHub Mobile for iOS or Android.
