### ISSUE TITLE
Data directories/DATA_ROOT?

### ISSUE THREAD

**Issue by deanishe** [piku/piku#357]
I'm trying to figure out Piku (the docs are pretty sparse, yo). It *looks* like Piku creates a persistent data directory for each application, but it doesn't appear to tell the app where the directory is.

Piku sets `NGINX_ROOT` and `LOG_ROOT` environment variables, but no `DATA_ROOT`.

What am I missing? Is that `.piku/data/<appname>` directory *not* for my app?

**Comment by rcarmo** [comment]
Hi, as you can see in https://github.com/piku/piku/blob/b9be24f09e085d08d4bab4a30bc4b691849cfff9/piku.py#L47 we do create it for the apps - I can’t recall why it is not passed on to the app environment, but it might just be an oversight - most apps we deploy tend to use databases and not file storage and thus there has been little need for it - you can just read the piku.py file and see where it is used and for what, and we’d welcome a pull request that sets it for the app.On 15 Jun 2024, at 08:27, Dean Jackson ***@***.***> wrote:﻿[piku/piku] Data directories/DATA_ROOT? (Issue #357)I'm trying to figure out Piku (the docs are pretty sparse, yo). It looks like Piku creates a persistent data directory for each application, but it doesn't appear to tell the app where the directory is.Piku sets NGINX_ROOT and LOG_ROOT environment variables, but no DATA_ROOT.What am I missing? Is that .piku/data/<appname> directory not for my app?—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you are subscribed to this thread.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chr15m** [comment]
Thought this was a pretty good idea from @deanishe so I went ahead and implemented it. I called it `DATA_PATH` but now I'm thinking maybe it should be `DATA_ROOT` like the other vars. :thinking:

**Comment by deanishe** [comment]
> we do create it for the apps

Yeah. Piku gave me [a message about preserving the app's data directory](https://github.com/piku/piku/blob/b9be24f09e085d08d4bab4a30bc4b691849cfff9/piku.py#L1430) when I destroyed an app, and I was like, "data directory?"

It looks like the feature was added, but never actually exposed to apps?

**Comment by chr15m** [comment]
Will update my PR shortly to make it consistent with the other vars. Thanks for the heads up.

**Comment by chr15m** [comment]
I've updated my PR now and it's a one-liner. I think it should be safe to merge but I will await any feedback from @rcarmo for a few days first.
