### ISSUE TITLE
Split off sample projects into separate repositories

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#91]
* [x] Define name spacing (`sample-language-app`)
* [ ] Create new repositories for each sample project
* [ ] Assign contributors to each repository

**Comment by rcarmo** [comment]
@chr15m, any suggestion for stuff like Gitea that isn't a sample? maybe `deploy-gitea`?

**Comment by chr15m** [comment]
@rcarmo what do you reckon about [piku-redirect](https://github.com/chr15m/piku-redirect/)? It is a utility app for simply redirecting from one url (like a www subdomain) to another URL. Should this be called `deploy-redirector` or `redirector` or `app-redirector`? :thinking:

**Comment by rcarmo** [comment]
I’m on the fence regarding that one, since I do the same straight from `nginx`. Why don’t we try to figure out how to do pure static sites (which involves injecting snippets into `nginx` anyway, possibly just pushing a config snippet) and move that functionality in there?

**Comment by chr15m** [comment]
Sounds good. I think there's a pretty strong case to be made for building redirect handling into the nginx portion of `piku.py` since redirecting from e.g. `www.` is pretty common. Likewise for server aliases (though that is getting out of scope).

**Comment by chr15m** [comment]
Related to this is #42. I am still thinking about the cleanest way to enable #42 so that it is trivial for the end user. I think it should be possible by making `spawn_app` happen even if there are no deployment types detected. Or treating detection of `index.html` in the root folder as a special deployment type where a static path of `/` is inferred.

On this topic: for the gitea deployment I had to create a `requirements.txt` even though Gitea is a single-binary deploy without any environment dependencies. This is because Piku currently requires at least one app environment before it will deploy an app. I can imagine many situations where people want a binary server deployment or just some static stuff served, and it would be good to give the user a way to flag this. For example, instead of printing this:

> -----> Could not detect runtime!

We could run `spawn_app` if `web` or `wsgi` and maybe a special `static` worker is defined, even if no app type is detected.
